import { useMemo } from 'react';

export default (t) => useMemo(() => ({
  id: {
    name: t('deviceIdentifier'),
    nameOriginal: 'deviceIdentifier',
    type: 'number',
    property: true,
  },
  latitude: {
    name: t('positionLatitude'),
    nameOriginal: 'positionLatitude',
    type: 'number',
    property: true,
  },
  longitude: {
    name: t('positionLongitude'),
    nameOriginal: 'positionLongitude',
    type: 'number',
    property: true,
  },
  speed: {
    name: t('positionSpeed'),
    nameOriginal: 'positionSpeed',
    type: 'number',
    dataType: 'speed',
    property: true,
  },
  course: {
    name: t('positionCourse'),
    nameOriginal: 'positionCourse',
    type: 'number',
    property: true,
  },
  altitude: {
    name: t('positionAltitude'),
    nameOriginal: 'positionAltitude',
    type: 'number',
    property: true,
  },
  accuracy: {
    name: t('positionAccuracy'),
    nameOriginal: 'positionAccuracy',
    type: 'number',
    dataType: 'distance',
    property: true,
  },
  valid: {
    name: t('positionValid'),
    nameOriginal: 'positionValid',
    type: 'boolean',
    property: true,
  },
  protocol: {
    name: t('positionProtocol'),
    nameOriginal: 'positionProtocol',
    type: 'string',
    property: true,
  },
  address: {
    name: t('positionAddress'),
    nameOriginal: 'positionAddress',
    type: 'string',
    property: true,
  },
  deviceTime: {
    name: t('positionDeviceTime'),
    nameOriginal: 'positionDeviceTime',
    type: 'string',
    property: true,
  },
  fixTime: {
    name: t('positionFixTime'),
    nameOriginal: 'positionFixTime',
    type: 'string',
    property: true,
  },
  serverTime: {
    name: t('positionServerTime'),
    nameOriginal: 'positionServerTime',
    type: 'string',
    property: true,
  },
  geofenceIds: {
    name: t('sharedGeofences'),
    nameOriginal: 'sharedGeofences',
    property: true,
  },
  raw: {
    name: t('positionRaw'),
    nameOriginal: 'positionRaw',
    type: 'string',
  },
  index: {
    name: t('positionIndex'),
    nameOriginal: 'positionIndex',
    type: 'number',
  },
  hdop: {
    name: t('positionHdop'),
    nameOriginal: 'positionHdop',
    type: 'number',
  },
  vdop: {
    name: t('positionVdop'),
    nameOriginal: 'positionVdop',
    type: 'number',
  },
  pdop: {
    name: t('positionPdop'),
    nameOriginal: 'positionPdop',
    type: 'number',
  },
  sat: {
    name: t('positionSat'),
    nameOriginal: 'positionSat',
    type: 'number',
  },
  satVisible: {
    name: t('positionSatVisible'),
    nameOriginal: 'positionSatVisible',
    type: 'number',
  },
  rssi: {
    name: t('positionRssi'),
    nameOriginal: 'positionRssi',
    type: 'number',
  },
  coolantTemp: {
    name: t('positionCoolantTemp'),
    nameOriginal: 'positionCoolantTemp',
    type: 'number',
  },
  gps: {
    name: t('positionGps'),
    nameOriginal: 'positionGps',
    type: 'number',
  },
  roaming: {
    name: t('positionRoaming'),
    nameOriginal: 'positionRoaming',
    type: 'boolean',
  },
  event: {
    name: t('positionEvent'),
    nameOriginal: 'positionEvent',
    type: 'string',
  },
  alarm: {
    name: t('positionAlarm'),
    nameOriginal: 'positionAlarm',
    type: 'string',
  },
  status: {
    name: t('positionStatus'),
    nameOriginal: 'positionStatus',
    type: 'string',
  },
  odometer: {
    name: t('positionOdometer'),
    nameOriginal: 'positionOdometer',
    type: 'number',
    dataType: 'distance',
  },
  serviceOdometer: {
    name: t('positionServiceOdometer'),
    nameOriginal: 'positionServiceOdometer',
    type: 'number',
    dataType: 'distance',
  },
  tripOdometer: {
    name: t('positionTripOdometer'),
    nameOriginal: 'positionTripOdometer',
    type: 'number',
    dataType: 'distance',
  },
  hours: {
    name: t('positionHours'),
    nameOriginal: 'positionHours',
    type: 'number',
    dataType: 'hours',
  },
  steps: {
    name: t('positionSteps'),
    nameOriginal: 'positionSteps',
    type: 'number',
  },
  heartRate: {
    name: t('positionHeartRate'),
    nameOriginal: 'positionHeartRate',
    type: 'number',
  },
  input: {
    name: t('positionInput'),
    nameOriginal: 'positionInput',
    type: 'number',
  },
  in1: {
    name: `${t('positionInput')} 1`,
    nameOriginal: `${'positionInput'} 1`,
    type: 'boolean',
  },
  in2: {
    name: `${t('positionInput')} 2`,
    nameOriginal: `${'positionInput'} 2`,
    type: 'boolean',
  },
  in3: {
    name: `${t('positionInput')} 3`,
    nameOriginal: `${'positionInput'} 3`,
    type: 'boolean',
  },
  in4: {
    name: `${t('positionInput')} 4`,
    nameOriginal: `${'positionInput'} 4`,
    type: 'boolean',
  },
  output: {
    name: t('positionOutput'),
    nameOriginal: 'positionOutput',
    type: 'number',
  },
  out1: {
    name: `${t('positionOutput')} 1`,
    nameOriginal: `${'positionOutput'} 1`,
    type: 'boolean',
  },
  out2: {
    name: `${t('positionOutput')} 2`,
    nameOriginal: `${'positionOutput'} 2`,
    type: 'boolean',
  },
  out3: {
    name: `${t('positionOutput')} 3`,
    nameOriginal: `${'positionOutput'} 3`,
    type: 'boolean',
  },
  out4: {
    name: `${t('positionOutput')} 4`,
    nameOriginal: `${'positionOutput'} 4`,
    type: 'boolean',
  },
  power: {
    name: t('positionPower'),
    nameOriginal: 'positionPower',
    type: 'number',
    dataType: 'voltage',
  },
  battery: {
    name: t('positionBattery'),
    nameOriginal: 'positionBattery',
    type: 'number',
    dataType: 'voltage',
  },
  batteryLevel: {
    name: t('positionBatteryLevel'),
    nameOriginal: 'positionBatteryLevel',
    type: 'number',
    dataType: 'percentage',
  },
  fuel: {
    name: t('positionFuel'),
    nameOriginal: 'positionFuel',
    type: 'number',
    dataType: 'volume',
  },
  fuelConsumption: {
    name: t('positionFuelConsumption'),
    nameOriginal: 'positionFuelConsumption',
    type: 'number',
  },
  versionFw: {
    name: t('positionVersionFw'),
    nameOriginal: 'positionVersionFw',
    type: 'string',
  },
  versionHw: {
    name: t('positionVersionHw'),
    nameOriginal: 'positionVersionHw',
    type: 'string',
  },
  type: {
    name: t('sharedType'),
    nameOriginal: 'sharedType',
    type: 'string',
  },
  ignition: {
    name: t('positionIgnition'),
    nameOriginal: 'positionIgnition',
    type: 'boolean',
  },
  flags: {
    name: t('positionFlags'),
    nameOriginal: 'positionFlags',
    type: 'string',
  },
  charge: {
    name: t('positionCharge'),
    nameOriginal: 'positionCharge',
    type: 'boolean',
  },
  ip: {
    name: t('positionIp'),
    nameOriginal: 'positionIp',
    type: 'string',
  },
  archive: {
    name: t('positionArchive'),
    nameOriginal: 'positionArchive',
    type: 'boolean',
  },
  distance: {
    name: t('positionDistance'),
    nameOriginal: 'positionDistance',
    type: 'number',
    dataType: 'distance',
  },
  totalDistance: {
    name: t('deviceTotalDistance'),
    nameOriginal: 'deviceTotalDistance',
    type: 'number',
    dataType: 'distance',
  },
  rpm: {
    name: t('positionRpm'),
    nameOriginal: 'positionRpm',
    type: 'number',
  },
  vin: {
    name: t('positionVin'),
    nameOriginal: 'positionVin',
    type: 'string',
  },
  approximate: {
    name: t('positionApproximate'),
    nameOriginal: 'positionApproximate',
    type: 'boolean',
  },
  throttle: {
    name: t('positionThrottle'),
    nameOriginal: 'positionThrottle',
    type: 'number',
  },
  motion: {
    name: t('positionMotion'),
    nameOriginal: 'positionMotion',
    type: 'boolean',
  },
  armed: {
    name: t('positionArmed'),
    nameOriginal: 'positionArmed',
    type: 'boolean',
  },
  geofence: {
    name: t('sharedGeofence'),
    nameOriginal: 'sharedGeofence',
    type: 'string',
  },
  acceleration: {
    name: t('positionAcceleration'),
    nameOriginal: 'positionAcceleration',
    type: 'number',
  },
  humidity: {
    name: t('positionHumidity'),
    nameOriginal: 'positionHumidity',
    type: 'number',
  },
  deviceTemp: {
    name: t('positionDeviceTemp'),
    nameOriginal: 'positionDeviceTemp',
    type: 'number',
  },
  temp1: {
    name: `${t('positionTemp')} 1`,
    nameOriginal: `${'positionTemp'} 1`,
    type: 'number',
  },
  temp2: {
    name: `${t('positionTemp')} 2`,
    nameOriginal: `${'positionTemp'} 2`,
    type: 'number',
  },
  temp3: {
    name: `${t('positionTemp')} 3`,
    nameOriginal: `${'positionTemp'} 3`,
    type: 'number',
  },
  temp4: {
    name: `${t('positionTemp')} 4`,
    nameOriginal: `${'positionTemp'} 4`,
    type: 'number',
  },
  operator: {
    name: t('positionOperator'),
    nameOriginal: 'positionOperator',
    type: 'string',
  },
  command: {
    name: t('deviceCommand'),
    nameOriginal: 'deviceCommand',
    type: 'string',
  },
  blocked: {
    name: t('positionBlocked'),
    nameOriginal: 'positionBlocked',
    type: 'boolean',
  },
  lock: {
    name: t('alarmLock'),
    nameOriginal: 'alarmLock',
    type: 'boolean',
  },
  dtcs: {
    name: t('positionDtcs'),
    nameOriginal: 'positionDtcs',
    type: 'string',
  },
  obdSpeed: {
    name: t('positionObdSpeed'),
    nameOriginal: 'positionObdSpeed',
    type: 'number',
    dataType: 'speed',
  },
  obdOdometer: {
    name: t('positionObdOdometer'),
    nameOriginal: 'positionObdOdometer',
    type: 'number',
    dataType: 'distance',
  },
  result: {
    name: t('eventCommandResult'),
    nameOriginal: 'eventCommandResult',
    type: 'string',
  },
  driverUniqueId: {
    name: t('sharedDriver'),
    nameOriginal: 'sharedDriver',
    type: 'string',
  },
  card: {
    name: t('positionCard'),
    nameOriginal: 'positionCard',
    type: 'string',
  },
  drivingTime: {
    name: t('positionDrivingTime'),
    nameOriginal: 'positionDrivingTime',
    type: 'number',
    dataType: 'hours',
  },
  color: {
    name: t('attributeColor'),
    nameOriginal: 'attributeColor',
    type: 'string',
  },
  image: {
    name: t('positionImage'),
    nameOriginal: 'positionImage',
    type: 'string',
  },
  video: {
    name: t('positionVideo'),
    nameOriginal: 'positionVideo',
    type: 'string',
  },
  audio: {
    name: t('positionAudio'),
    nameOriginal: 'positionAudio',
    type: 'string',
  },
}), [t]);
